@extends('layouts.super_admin', ['pageTitle' => 'Fee Receipt'])

@section('page_styles')
<style>
    .receipt-card { max-width: 760px; margin: 0 auto; border: 1px solid #dbe3f1; border-radius: 12px; padding: 2rem; }
    @media print { .sidebar, .topbar, .print-button { display:none !important; } .main-content { margin:0; padding:0; } .content-area { box-shadow:none; padding:0; } .receipt-card { border:0; max-width:none; } }
</style>
@endsection

@section('super_admin_content')
<div class="d-flex justify-content-end mb-3"><button onclick="window.print()" class="btn btn-outline-primary print-button"><i class="bi bi-printer me-2"></i>Print Receipt</button></div>
<div class="receipt-card">
    <div class="text-center border-bottom pb-3 mb-4"><i class="bi bi-mortarboard-fill fs-1 text-warning"></i><h2 class="text-navy mb-1">EduPulse School</h2><p class="text-muted mb-0">Official Fee Payment Receipt</p></div>
    <div class="d-flex justify-content-between mb-4"><div><div class="detail-label">Receipt Number</div><div class="fw-bold">{{ $payment->receipt_number }}</div></div><div class="text-end"><div class="detail-label">Payment Date</div><div class="fw-bold">{{ $payment->payment_date->format('M d, Y') }}</div></div></div>
    <div class="row g-3">
        @foreach ([['Student Name', $payment->student->full_name], ['Admission Number', $payment->student->admission_number], ['Class / Section', $payment->assignment->schoolClass->name.' / '.$payment->assignment->schoolSection->name], ['Fee Type', $payment->assignment->feeType->name], ['Paid Amount', number_format($payment->payment_amount, 2)], ['Payment Method', $methods[$payment->payment_method]], ['Balance Amount', number_format($payment->assignment->balance_amount, 2)], ['Received By', $payment->receiver->first_name.' '.$payment->receiver->last_name]] as [$label, $value])
        <div class="col-md-6"><div class="p-3 bg-light rounded"><div class="detail-label">{{ $label }}</div><div class="fw-semibold">{{ $value }}</div></div></div>
        @endforeach
    </div>
    @if ($payment->reference_number || $payment->remarks)<div class="mt-4 pt-3 border-top">@if ($payment->reference_number)<p><strong>Reference:</strong> {{ $payment->reference_number }}</p>@endif @if ($payment->remarks)<p class="mb-0"><strong>Remarks:</strong> {{ $payment->remarks }}</p>@endif</div>@endif
    <div class="text-center text-muted small mt-5">This receipt was generated by the School Management System.</div>
</div>
@endsection
