@extends('layouts.super_admin', ['pageTitle' => Auth::user()->role === 'student' ? 'My Fees' : 'Student Fee List'])

@section('super_admin_content')
@php($isManager = in_array(Auth::user()->role, ['super_admin', 'admin'], true))
<div class="page-heading"><div><h1>{{ $isManager ? 'Student Fee List' : 'My Fees' }}</h1><p>Track assigned amounts, payments, balances, and due dates.</p></div>@if ($isManager)<a href="{{ route('fees.assign') }}" class="btn btn-academic"><i class="bi bi-plus-lg me-2"></i>Assign Fees</a>@endif</div>
@if ($isManager)
<form method="GET" class="row g-2 mb-4">
    <div class="col-lg-2"><select name="class_id" class="form-select"><option value="">All classes</option>@foreach ($classes as $class)<option value="{{ $class->id }}" @selected((string) request('class_id') === (string) $class->id)>{{ $class->name }}</option>@endforeach</select></div>
    <div class="col-lg-2"><select name="section_id" class="form-select"><option value="">All sections</option>@foreach ($classes as $class)@foreach ($class->sections as $section)<option value="{{ $section->id }}" @selected((string) request('section_id') === (string) $section->id)>{{ $class->name }} - {{ $section->name }}</option>@endforeach @endforeach</select></div>
    <div class="col-lg-2"><select name="student_id" class="form-select"><option value="">All students</option>@foreach ($students as $student)<option value="{{ $student->id }}" @selected((string) request('student_id') === (string) $student->id)>{{ $student->full_name }}</option>@endforeach</select></div>
    <div class="col-lg-2"><select name="fee_type_id" class="form-select"><option value="">All fee types</option>@foreach ($feeTypes as $type)<option value="{{ $type->id }}" @selected((string) request('fee_type_id') === (string) $type->id)>{{ $type->name }}</option>@endforeach</select></div>
    <div class="col-lg-2"><select name="payment_status" class="form-select"><option value="">All statuses</option>@foreach ($paymentStatuses as $value => $label)<option value="{{ $value }}" @selected(request('payment_status') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-lg-2 d-flex gap-2"><button class="btn btn-academic flex-grow-1">Filter</button><a href="{{ route('fees.assignments.index') }}" class="btn btn-outline-secondary">Clear</a></div>
</form>
@endif
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Student</th><th>Class / Section</th><th>Fee Type</th><th>Total</th><th>Paid</th><th>Balance</th><th>Due Date</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse ($assignments as $assignment)<tr class="{{ $assignment->payment_status === 'overdue' ? 'table-danger' : '' }}"><td><span class="fw-semibold">{{ $assignment->student->full_name }}</span><br><small class="text-muted">{{ $assignment->student->admission_number }}</small></td><td>{{ $assignment->schoolClass->name }} / {{ $assignment->schoolSection->name }}</td><td>{{ $assignment->feeType->name }}<br><small class="text-muted">{{ $assignment->academic_year }}</small></td><td>{{ number_format($assignment->assigned_amount, 2) }}</td><td>{{ number_format($assignment->paid_amount, 2) }}</td><td class="fw-semibold">{{ number_format($assignment->balance_amount, 2) }}</td><td>{{ $assignment->due_date->format('M d, Y') }}</td><td><span class="status-badge status-{{ $assignment->payment_status }}">{{ $paymentStatuses[$assignment->payment_status] }}</span></td><td><div class="d-flex justify-content-end gap-1"><a href="{{ route('fees.assignments.show', $assignment) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a>@if ($isManager && $assignment->balance_amount > 0)<a href="{{ route('fees.payments.create', $assignment) }}" class="btn btn-sm btn-outline-success"><i class="bi bi-cash-coin"></i></a>@endif @if ($isManager)<a href="{{ route('fees.assign', ['edit' => $assignment->id]) }}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('fees.assignments.destroy', $assignment) }}" onsubmit="return confirm('Delete this fee assignment?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form>@endif</div></td></tr>
@empty<tr><td colspan="9"><div class="empty-state"><i class="bi bi-receipt"></i><h5>No fee assignments found</h5></div></td></tr>@endforelse
</tbody></table></div>
@if ($assignments->hasPages())<div class="mt-4">{{ $assignments->links() }}</div>@endif
@endsection
