@extends('layouts.super_admin', ['pageTitle' => 'Attendance Report'])
@section('super_admin_content')
@include('reports._styles')
<div class="page-heading"><div><h1>Attendance Report</h1><p>Daily totals and student-wise attendance performance.</p></div>@include('reports._toolbar')</div>
<div class="card report-card mb-4 report-filters"><div class="card-body"><form class="row g-3">@include('reports._common_filters', ['fields' => ['academic_year','class_id','section_id','student_id']])<div class="col-md-3"><label class="form-label">From</label><input type="date" name="date_from" value="{{ request('date_from') }}" class="form-control"></div><div class="col-md-3"><label class="form-label">To</label><input type="date" name="date_to" value="{{ request('date_to') }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">All statuses</option>@foreach(['present','absent','late'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-12 d-flex gap-2"><button class="btn btn-academic">Apply Filters</button><a href="{{ route('reports.attendance') }}" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<div class="card report-card mb-4"><div class="card-header bg-white fw-semibold">Student-wise Summary</div><div class="card-body table-responsive"><table class="table table-hover report-table"><thead><tr><th>Student</th><th>Class / Section</th><th>Total</th><th>Present</th><th>Absent</th><th>Late</th><th>Attendance</th></tr></thead><tbody>@forelse($attendanceRows as $row)<tr><td class="fw-semibold">{{ $row->student?->full_name }}</td><td>{{ $row->schoolClass?->name }} / {{ $row->schoolSection?->name }}</td><td>{{ $row->total_days }}</td><td>{{ $row->present_days }}</td><td>{{ $row->absent_days }}</td><td>{{ $row->late_days }}</td><td>{{ $row->total_days ? number_format(($row->present_days/$row->total_days)*100, 1) : 0 }}%</td></tr>@empty<tr><td colspan="7" class="text-center py-5 text-muted">No attendance records found.</td></tr>@endforelse</tbody></table></div></div>
<div class="card report-card"><div class="card-header bg-white fw-semibold">Daily Summary</div><div class="card-body table-responsive"><table class="table report-table"><thead><tr><th>Date</th><th>Total</th><th>Present</th><th>Absent</th><th>Late</th></tr></thead><tbody>@forelse($dailySummary as $day)<tr><td>{{ \Carbon\Carbon::parse($day->attendance_date)->format('M d, Y') }}</td><td>{{ $day->total }}</td><td>{{ $day->present }}</td><td>{{ $day->absent }}</td><td>{{ $day->late }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">No daily records.</td></tr>@endforelse</tbody></table></div></div>
@if($attendanceRows->hasPages())<div class="mt-4">{{ $attendanceRows->links() }}</div>@endif
@endsection
