@extends('layouts.super_admin', ['pageTitle' => 'Fee Report'])
@section('super_admin_content')
@include('reports._styles')
<div class="page-heading"><div><h1>Fee Report</h1><p>Assigned fees, collections, balances, and payment status.</p></div>@include('reports._toolbar')</div>
<div class="row g-3 mb-4">@foreach(['assigned'=>'Assigned','paid'=>'Collected','balance'=>'Outstanding'] as $key=>$label)<div class="col-md-4"><div class="card report-card report-metric"><div class="card-body"><small class="text-muted">{{ $label }}</small><h3 class="mb-0">{{ number_format($feeTotals->$key ?? 0, 2) }}</h3></div></div></div>@endforeach</div>
<div class="card report-card mb-4 report-filters"><div class="card-body"><form class="row g-3">@include('reports._common_filters', ['fields' => ['academic_year','class_id','section_id','student_id']])<div class="col-md-3"><label class="form-label">Fee Type</label><select name="fee_type_id" class="form-select"><option value="">All types</option>@foreach($feeTypes as $type)<option value="{{ $type->id }}" @selected((string)request('fee_type_id')===(string)$type->id)>{{ $type->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Payment Status</label><select name="payment_status" class="form-select"><option value="">All statuses</option>@foreach(['unpaid','partially_paid','paid','overdue'] as $status)<option value="{{ $status }}" @selected(request('payment_status')===$status)>{{ ucwords(str_replace('_',' ',$status)) }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Due From</label><input type="date" name="date_from" value="{{ request('date_from') }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Due To</label><input type="date" name="date_to" value="{{ request('date_to') }}" class="form-control"></div><div class="col-12 d-flex gap-2"><button class="btn btn-academic">Apply Filters</button><a href="{{ route('reports.fees') }}" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<div class="card report-card"><div class="card-body table-responsive"><table class="table table-hover report-table"><thead><tr><th>Student</th><th>Fee Type</th><th>Year</th><th>Class</th><th>Assigned</th><th>Paid</th><th>Balance</th><th>Due</th><th>Status</th></tr></thead><tbody>@forelse($feeRows as $fee)<tr><td class="fw-semibold">{{ $fee->student?->full_name }}</td><td>{{ $fee->feeType?->name }}</td><td>{{ $fee->academic_year }}</td><td>{{ $fee->schoolClass?->name }} / {{ $fee->schoolSection?->name }}</td><td>{{ number_format($fee->assigned_amount,2) }}</td><td>{{ number_format($fee->paid_amount,2) }}</td><td>{{ number_format($fee->balance_amount,2) }}</td><td>{{ $fee->due_date?->format('M d, Y') }}</td><td>{{ ucwords(str_replace('_',' ',$fee->payment_status)) }}</td></tr>@empty<tr><td colspan="9" class="text-center py-5 text-muted">No fee records found.</td></tr>@endforelse</tbody></table></div></div>
@if($feeRows->hasPages())<div class="mt-4">{{ $feeRows->links() }}</div>@endif
@endsection
