@extends('layouts.super_admin', ['pageTitle' => 'Marks Report'])
@section('super_admin_content')
@include('reports._styles')
<div class="page-heading"><div><h1>Marks Report</h1><p>Student marks and performance by exam, class, and subject.</p></div>@include('reports._toolbar')</div>
<div class="row g-3 mb-4"><div class="col-md-6"><div class="card report-card report-metric"><div class="card-body"><small class="text-muted">Records</small><h3 class="mb-0">{{ $markTotals->records ?? 0 }}</h3></div></div></div><div class="col-md-6"><div class="card report-card report-metric"><div class="card-body"><small class="text-muted">Average Percentage</small><h3 class="mb-0">{{ number_format($markTotals->average ?? 0, 1) }}%</h3></div></div></div></div>
<div class="card report-card mb-4 report-filters"><div class="card-body"><form class="row g-3">@include('reports._common_filters', ['fields' => ['academic_year','class_id','section_id','student_id','subject_id']])<div class="col-md-3"><label class="form-label">Exam</label><select name="exam_id" class="form-select"><option value="">All exams</option>@foreach($examsFilter as $exam)<option value="{{ $exam->id }}" @selected((string)request('exam_id')===(string)$exam->id)>{{ $exam->exam_name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Grade</label><select name="grade" class="form-select"><option value="">All grades</option>@foreach(['A','B','C','S','F'] as $grade)<option value="{{ $grade }}" @selected(request('grade')===$grade)>{{ $grade }}</option>@endforeach</select></div><div class="col-12 d-flex gap-2"><button class="btn btn-academic">Apply Filters</button><a href="{{ route('reports.marks') }}" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<div class="card report-card"><div class="card-body table-responsive"><table class="table table-hover report-table"><thead><tr><th>Student</th><th>Exam</th><th>Subject</th><th>Class</th><th>Marks</th><th>Percentage</th><th>Grade</th><th>Status</th></tr></thead><tbody>@forelse($markRows as $mark)<tr><td class="fw-semibold">{{ $mark->student?->full_name }}</td><td>{{ $mark->exam?->exam_name }}</td><td>{{ $mark->subject?->name }}</td><td>{{ $mark->schoolClass?->name }} / {{ $mark->schoolSection?->name }}</td><td>{{ $mark->marks_obtained }} / {{ $mark->maximum_marks }}</td><td>{{ $mark->maximum_marks ? number_format(($mark->marks_obtained/$mark->maximum_marks)*100, 1) : 0 }}%</td><td><span class="badge text-bg-{{ $mark->grade === 'F' ? 'danger' : 'primary' }}">{{ $mark->grade }}</span></td><td>{{ ucfirst($mark->status) }}</td></tr>@empty<tr><td colspan="8" class="text-center py-5 text-muted">No marks found.</td></tr>@endforelse</tbody></table></div></div>
@if($markRows->hasPages())<div class="mt-4">{{ $markRows->links() }}</div>@endif
@endsection
