@extends('layouts.super_admin', ['pageTitle' => 'Notice Management'])
@section('super_admin_content')
<div class="page-heading"><div><h1>Notice List</h1><p>Manage school announcements and audience-specific messages.</p></div><a href="{{ route('notices.create') }}" class="btn btn-academic"><i class="bi bi-plus-lg me-2"></i>Add Notice</a></div>
<form method="GET" class="row g-2 mb-4"><div class="col-lg-4"><input type="search" name="search" class="form-control" value="{{ request('search') }}" placeholder="Search notice title"></div><div class="col-lg-2"><select name="audience" class="form-select"><option value="">All audiences</option>@foreach ($audiences as $value => $label)<option value="{{ $value }}" @selected(request('audience') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-lg-2"><select name="status" class="form-select"><option value="">All statuses</option>@foreach ($statuses as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-lg-2"><input type="date" name="date" class="form-control" value="{{ request('date') }}"></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-academic flex-grow-1">Filter</button><a href="{{ route('notices.index') }}" class="btn btn-outline-secondary">Clear</a></div></form>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Title</th><th>Audience</th><th>Publish Date</th><th>Expiry Date</th><th>Priority</th><th>Status</th><th>Created By</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse ($notices as $notice)<tr><td class="fw-semibold">{{ $notice->title }}</td><td>{{ $audiences[$notice->audience] }}@if ($notice->schoolClass)<br><small class="text-muted">{{ $notice->schoolClass->name }}{{ $notice->schoolSection ? ' / '.$notice->schoolSection->name : '' }}</small>@endif</td><td>{{ $notice->publish_date->format('M d, Y') }}</td><td>{{ $notice->expiry_date?->format('M d, Y') ?? 'No expiry' }}</td><td><span class="status-badge priority-{{ $notice->priority }}">{{ $priorities[$notice->priority] }}</span></td><td>@if ($notice->is_expired)<span class="status-badge status-inactive">Expired</span>@else<span class="status-badge status-{{ $notice->status }}">{{ $statuses[$notice->status] }}</span>@endif</td><td>{{ $notice->creator->first_name }} {{ $notice->creator->last_name }}</td><td><div class="d-flex justify-content-end gap-1"><a href="{{ route('notices.show', $notice) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a><a href="{{ route('notices.edit', $notice) }}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('notices.publish', $notice) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $notice->status === 'published' ? 'btn-outline-warning' : 'btn-outline-success' }}" title="{{ $notice->status === 'published' ? 'Unpublish' : 'Publish' }}"><i class="bi {{ $notice->status === 'published' ? 'bi-pause-circle' : 'bi-send' }}"></i></button></form><form method="POST" action="{{ route('notices.destroy', $notice) }}" onsubmit="return confirm('Delete this notice?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div></td></tr>
@empty<tr><td colspan="8"><div class="empty-state"><i class="bi bi-megaphone"></i><h5>No notices found</h5></div></td></tr>@endforelse
</tbody></table></div>
@if ($notices->hasPages())<div class="mt-4">{{ $notices->links() }}</div>@endif
@endsection
